### PR TITLE
Dashboard projects

### PR DESCRIPTION
**Pull request by Omcci**
WIP Dashboard link backend to frontend : 
- Create a reusable modal component (in lib)
- Add query and mutation to handle projects

### Merge/review  before this PR:
- #48 (gql init)  
- #44 (tile component) 
- #51 (get props of codesnippet)

### CODE REVIEW

**Comment by Omcci** [comment]
Capture d’écran 2024-04-01 à 18 42 58

TODO : Fix = when clicking on 'Tout voir' then clicking on the bin, it doesn't show the modal.

**Comment by Omcci** [comment]
TODO : Suggesting adding a description field for the project, or define the description based on a code snippet.

**Comment by Omcci** [comment]
Fix the modal issue inside dashboardProject
Commit : https://github.com/neolink78/Editoria/pull/53/commits/a9fabd163422f73c4feb3859e1112666795ddc4f
Capture d’écran 2024-04-07 à 15 58 17

**Comment by Omcci** [comment]
Add pagination for DashboardProject
Commit : https://github.com/neolink78/Editoria/pull/53/commits/cd51ae526fd7a3a207702b82b54c017dc80cfc0c
Capture d’écran 2024-04-07 à 16 15 01

**Comment by Omcci** [comment]
Commit : https://github.com/neolink78/Editoria/pull/53/commits/1b13367d6947b94cfa9c98596760618c13b017fa
[Add skeleton for when loading content](https://github.com/neolink78/Editoria/pull/53/commits/1b13367d6947b94cfa9c98596760618c13b017fa)
Capture d’écran 2024-04-07 à 22 39 29

**Comment by Omcci** [comment]
[Update pagination look and create svg for right arrow](https://github.com/neolink78/Editoria/pull/53/commits/ab91750c46c04d862a0d4fffc149f38f14e58e2e)Capture d’écran 2024-04-07 à 22 37 15

**Review by Chl0l — DISMISSED** [review]

**Review by T0MLE — APPROVED** [review]

**Review by neolink78 — APPROVED** [review]

**Pull request merged**
